### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Yaya7** [pablopunk/livesoccertv-parser#7]
Hi thanks for the repo pls let me know if there any way to parse this  page http://www.livesoccertv.com/schedules/  by leagues thanks

**Comment by pablopunk** [comment]
@Yaya7 I guess I could do that in the future

**Comment by leiaaloha** [comment]
By chance did you look at parsing the schedules ? or by Channels?

**Comment by pablopunk** [comment]
@leiaaloha I haven't updated this repo in a while since it already fits my needs. You're free to open a PR if you feel like you can tackle your issue.

Also, please describe exactly what you wanna achieve here, so someone (or myself) might be able to build that feature.

**Comment by pablopunk** [comment]
I'll close this issue. Feel free to open it again if someone's gonna take it
